//
//  ViewController.swift
//  ProjectforOldman
//
//  Created by Peem on 26/5/2563 BE.
//  Copyright © 2563 Peem. All rights reserved.
//

import UIKit

class ViewController: UIViewController
{
    
    @IBOutlet weak var Label: UILabel!
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        
        Label.text = "gfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjfdgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjfdgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbjgfgtrvfbrfrrvmfovneivvevremvkofenvifenvfnifnvfrnifrnjfnjifnojfrnifnjbinrfuifrnbjfnubfnkbnfibnfdobjfiojbfihbifdjbhiofdjbofdjfdbj"
        
    }


}

